# Generated by Django 5.2.1 on 2025-12-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_security_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('master', 'Master'), ('superadmin', 'Super Admin'), ('masteradmin', 'Master Admin'), ('projectadmin', 'Project Admin'), ('adminuser', 'Admin User')], max_length=20),
        ),
    ]
