# Generated by Django 5.2.1 on 2025-12-28 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('induction', 'Induction Training'), ('ptw', 'Permit to Work'), ('incident', 'Incident Report'), ('safety_observation', 'Safety Observation'), ('toolbox_talk', 'Toolbox Talk'), ('mom', 'Minutes of Meeting')], max_length=50)),
                ('form_id', models.PositiveIntegerField(help_text='ID of the signed form')),
                ('signature_hash', models.CharField(help_text='SHA256 hash for integrity', max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('form_type', 'form_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SignatureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Signature Created'), ('used', 'Signature Used'), ('verified', 'Signature Verified'), ('printed', 'Document Printed')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('form_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.formsignature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(help_text="User's digital signature image", upload_to='signatures/digital/')),
                ('signature_data', models.TextField(help_text='Base64 signature data for backup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
