# Generated by Django 5.2.1 on 2025-12-28 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_formsignature_signatureauditlog_usersignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=50)),
                ('form_id', models.PositiveIntegerField()),
                ('signature_type', models.CharField(choices=[('trainer', 'Trainer'), ('hr', 'HR Representative'), ('safety', 'Safety Officer'), ('dept_head', 'Department Head'), ('worker', 'Worker Verification')], max_length=20)),
                ('requested_for_name', models.CharField(help_text='Name of person to sign (for workers without accounts)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('form_type', 'form_id', 'signature_type')},
            },
        ),
    ]
