# Generated by Django 5.2.1 on 2025-12-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_signaturerequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='authenticat_user_id_4528f8_idx'),
        ),
    ]
