# Generated by Django 5.2.1 on 2025-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_notification_privacy_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('master', 'Master'), ('projectadmin', 'Project Admin'), ('adminuser', 'Admin User')], max_length=20),
        ),
    ]
