#!/bin/bash

# Google Drive Service Account Setup for Athens EHS Backups

echo "=== Google Drive Service Account Setup ==="
echo ""
echo "To set up automated Google Drive backups, you need to:"
echo ""
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo "2. Create a new project or select existing project"
echo "3. Enable Google Drive API"
echo "4. Create Service Account:"
echo "   - Go to IAM & Admin > Service Accounts"
echo "   - Click 'Create Service Account'"
echo "   - Name: athens-backup-service"
echo "   - Click 'Create and Continue'"
echo "   - Skip role assignment (click 'Continue')"
echo "   - Click 'Done'"
echo ""
echo "5. Create Service Account Key:"
echo "   - Click on the created service account"
echo "   - Go to 'Keys' tab"
echo "   - Click 'Add Key' > 'Create new key'"
echo "   - Choose 'JSON' format"
echo "   - Download the JSON file"
echo ""
echo "6. Share Google Drive folder with service account:"
echo "   - Create folder 'athens_backups' in your Google Drive"
echo "   - Right-click folder > Share"
echo "   - Add service account email (from JSON file)"
echo "   - Give 'Editor' permission"
echo ""
echo "7. Upload the JSON key file to this server:"
echo "   From your local computer:"
echo "   scp service-account-key.json root@prozeal.athenas.co.in:/var/www/athens/gdrive-service-account.json"
echo ""
echo "   OR use nano to paste the JSON content:"
echo "   nano /var/www/athens/gdrive-service-account.json"
echo "   (Copy and paste the entire JSON file content)"
echo ""
echo "8. Run: /var/www/athens/setup_gdrive_service.sh"
echo ""