# Generated by Django 5.2.1 on 2025-12-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_signaturerequest'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityinspection',
            name='project_id',
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='site_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='authentication.project'),
        ),
        migrations.AddField(
            model_name='qualitytemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_templates', to='authentication.project'),
        ),
    ]
