"""
Secure authentication views with proper password handling
"""
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .views import CustomTokenObtainPairView
from .auth_utils import create_secure_admin_password, validate_password_reset_request, secure_password_response
import base64


def secure_create_admin_user(request_data, project, admin_type, company_data=None):
    """Securely create admin user with strong password"""
    password = create_secure_admin_password()
    
    admin_data = {
        'username': request_data.get(f'{admin_type}_username'),
        'password': password,
        'user_type': 'projectadmin',
        'project': project.id,
        'admin_type': admin_type,
        'company_name': company_data.get('company_name') if company_data else None,
        'registered_address': company_data.get('registered_address') if company_data else None,
        'is_autogenerated_password': True,
        'is_password_reset_required': True,
        'is_active': True,
    }
    
    return admin_data, password


def secure_password_reset(request):
    """Securely handle password reset with validation"""
    password_valid, message = validate_password_reset_request(request.data)
    
    if not password_valid:
        return secure_password_response(False, message)
    
    return None  # No error, proceed with reset


class SecureCompatibleLoginAPIView(APIView):
    """Secure login view that's backward compatible with existing frontend"""
    
    def post(self, request, *args, **kwargs):
        """Handle secure login with backward compatibility"""
        from .serializers import CustomTokenObtainPairSerializer
        
        # Check if request contains encoded credentials
        if 'credentials' in request.data:
            try:
                # Decode the credentials
                encoded_creds = request.data['credentials']
                decoded_creds = base64.b64decode(encoded_creds).decode('utf-8')
                username, password = decoded_creds.split(':', 1)
                
                # Create login data
                login_data = {'username': username, 'password': password}
                
            except Exception as e:
                return Response({'detail': f'Invalid credentials format: {str(e)}'}, status=400)
        else:
            # Use regular username/password
            login_data = request.data
        
        # Use the serializer directly
        serializer = CustomTokenObtainPairSerializer(data=login_data)
        if serializer.is_valid():
            return Response(serializer.validated_data, status=200)
        else:
            return Response({'detail': 'Invalid username or password.'}, status=400)