# Generated by Django 5.2.1 on 2025-12-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, help_text='User who witnessed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_witnessed', to=settings.AUTH_USER_MODEL),
        ),
    ]
