# Generated by Django 5.2.1 on 2025-12-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_user_type'),
        ('safetyobservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_observations', to='authentication.project'),
        ),
    ]
