# Generated by Django 5.2.1 on 2025-12-27 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0002_safetyobservation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='escalation_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
